name: Binwalk Action

on: [push]

jobs:
  binwalk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install binwalk
      run: |
        apt-get update && apt-get install binwalk
    - name: Download file from URL
      run: curl -L -o file.bin "${{ inputs.url }}"
    - name: Scan and extract embedded files with binwalk
      run: binwalk -e file.bin
