# This is a basic workflow that is manually triggered

name: Binwalk
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      url:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'URL to binwalk'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  binwalk:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.3.0
    - name: Install Binwalk
      run: |
       git clone https://github.com/ReFirmLabs/binwalk.git
       cd binwalk
       sudo python3 setup.py install
     - name: Binwalk the file
      run: |
       cd /home/
       curl ${{ github.event.inputs.url }} -o bintowalk.bin
       binwalk bintowalk.bin --signature -A -Y --dd='.*'
       rm bintowalk.bin
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: binwalks
          path: | home/
